### ISSUE TITLE
Add asterisk to students

### ISSUE THREAD

**Issue by kousu** [neuropoly/bibeasy#7]
In https://ccv-cvc.ca it's suggested (by whom?) to mark supervised students with a `*` in the Authors field.

The [googlesheet](https://docs.google.com/spreadsheets/d/1dEUBYf17hNM22dqV4zx1gsh3Q-d97STnRB4q7p9nQ54/edit#gid=566297787)

you can see several of these disagreements found by my [`bibeasy sync` work](https://github.com/jcohenadad/bibeasy/pull/13#issuecomment-945035778), e.g.

```diff
-Noriega de la Colina A, Badji A*, Robitaille-Grou MC, Gagnon C, Boshkovski T, Lamarre-Cliche M, Joubert S, Gauthier C, Bherer L, Cohen-Adad J, Girouard H
+Noriega de la Colina A, Badji A, Robitaille-Grou MC, Gagnon C, Boshkovski T, Lamarre-Cliche M, Joubert S, Gauthier C, Bherer L, Cohen-Adad J, Girouard H
```

```diff
-Mangeat G*, Ouellette R, Wabartha M, De Leener B, Plattén M, Danylaité Karrenbauer V, Warntjes M, Stikov N, Mainero C, Cohen-Adad J, Granberg T
+Mangeat G, Ouellette R, Wabartha M, De Leener B, Plattén M, Danylaité Karrenbauer V, Warntjes M, Stikov N, Mainero C, Cohen-Adad J, Granberg T
```

We don't want to throw away this information since CCV needs it.

@jcohenadad and I talked about several solutions:

1. `bibeasy` currently maintains a list of names hard-coded into the code:

    https://github.com/jcohenadad/bibeasy/blob/637635b5e14ccc30bf71a9af491a1e8484393864/bibeasy/formatting.py#L13-L53

   I'm not sure everywhere this is used, but presumably it was added with the thought that papers would automatically.

    This has a lurking bug though: if a student graduates to being a collaborator, either in the lab or with a different lab, they will forever be marked as a student even on all future publications. Which is probably not ideal.

2. Add a "Students" column to the googlesheet, per-paper.

    This would solve it, but it would be a maintenance burden.

3. Add the `*`s directly to the Authors fields on the googlesheet.

    This would mean syncing with CCV is easy. But it means exporting to .docx or wiki formats (for https://www.neuro.polymtl.ca/publications) will end up with `*`s and, in those contexts, we *don't* want them. My proposed solution to this is just: when exporting to those formats filter out the stars; but when exporting to CCV, keep them.

My suggestion is to do 3. We can use the XML diff from neuropoly/bibeasy-old#13 or maybe write a quick one-off script (which I've already got part of done in the comments in neuropoly/bibeasy#8) to match up slightly-wrong authors lists and see what needs manual updating in the googlesheet. Then we would drop the students list from the code, and when rewriting the wiki exporter (which needs to be rewritten anyway, since we moved our docs from dokuwiki to markdown) just make sure to add `authors.replace('*','')` at the appropriate place.

**Comment by jcohenadad** [comment]
> This has a lurking bug though: if a student graduates to being a collaborator, either in the lab or with a different lab, they will forever be marked as a student even on all future publications. Which is probably not ideal.

this was well anticipated by @kousu, and is now an issue #17

**Comment by jcohenadad** [comment]
Fixed in https://github.com/neuropoly/bibeasy/pull/20
